export const ipoData = [
  {
    id: 1,
    company: 'GO AIR',
    logo: '/img/oyo.png', // example logo
    issueDate: '4th - 7th Oct 2022',
    issueSize: '₹3600 Crores',
    priceRange: '₹50-60',
    minInvestment: '₹50,000',
    lots: '100 Shares/5 Lots',
    details: {
      issueSize: '₹3,600 - 3,700 Cr.',
      priceRange: '₹100 - 200',
      minAmount: '₹50,000',
      lotSize: '150 shares/lots',
      issueDates: '12 Dec - 15 Dec 22',
      listedOn: '15 Dec 22',
      listedPrice: '₹150',
      listingGains: '₹10 (10.0%)',
      timeline: [
        { name: 'Bidding starts', date: '12 Dec 2023' },
        { name: 'Bidding ends', date: '15 Dec 2023' },
        { name: 'Allotment finalization', date: '18 Dec 2023' },
        { name: 'Refund initiation', date: '18 Dec 2023' },
        { name: 'Demat transfer', date: '18 Dec 2023' },
        { name: 'Listing date', date: '21 Dec 2023' },
      ],
      about:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore.',
    },
  },
  {
    id: 2,
    company: 'BAJAJ ENERGY',
    logo: 'https://companieslogo.com/img/orig/BAJEL-28b34422.png?t=1721234567',
    issueDate: '4th - 7th Oct 2022',
    issueSize: '₹3600 Crores',
    priceRange: '₹50-60',
    minInvestment: '₹50,000',
    lots: '100 Shares/5 Lots',
    details: {
      issueSize: '₹3,600 - 3,700 Cr.',
      priceRange: '₹100 - 200',
      minAmount: '₹50,000',
      lotSize: '150 shares/lots',
      issueDates: '12 Dec - 15 Dec 22',
      listedOn: '15 Dec 22',
      listedPrice: '₹150',
      listingGains: '₹10 (10.0%)',
      timeline: [
        { name: 'Bidding starts', date: '12 Dec 2023' },
        { name: 'Bidding ends', date: '15 Dec 2023' },
        { name: 'Allotment finalization', date: '18 Dec 2023' },
        { name: 'Refund initiation', date: '18 Dec 2023' },
        { name: 'Demat transfer', date: '18 Dec 2023' },
        { name: 'Listing date', date: '21 Dec 2023' },
      ],
      about:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore.',
    },
  },
  {
    id: 3,
    company: 'OYO',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/4/44/OYO_Rooms_logo.png',
    issueDate: 'To be announced',
    issueSize: '₹3600 Crores',
    priceRange: '₹50-60',
    minInvestment: '₹50,000',
    lots: '100 Shares/5 Lots',
    details: {
      issueSize: '₹3,600 - 3,700 Cr.',
      priceRange: '₹100 - 200',
      minAmount: '₹50,000',
      lotSize: '150 shares/lots',
      issueDates: '12 Dec - 15 Dec 22',
      listedOn: '15 Dec 22',
      listedPrice: '₹150',
      listingGains: '₹10 (10.0%)',
      timeline: [
        { name: 'Bidding starts', date: '12 Dec 2023' },
        { name: 'Bidding ends', date: '15 Dec 2023' },
        { name: 'Allotment finalization', date: '18 Dec 2023' },
        { name: 'Refund initiation', date: '18 Dec 2023' },
        { name: 'Demat transfer', date: '18 Dec 2023' },
        { name: 'Listing date', date: '21 Dec 2023' },
      ],
      about:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore.',
    },
  },
];
